// lib/mock-data.ts
import {
  AppCardData,
  AppWithSlug,
  EnumAppSource,
  EnumAppStatus,
  EnumAppType,
  EnumPlatformType,
} from './types.app';

// ─── Main app ───────────────────────────────────────────────────────────────

export const mockApp: AppWithSlug = {
  slug: 'pandavpn-lite-free-fast-vpn',
  name: 'PandaVPN Lite',
  title: 'PandaVPN Lite – Free, Fast & Secure VPN',
  // FIX: was `'android' as any` — now correctly typed via EnumPlatformType
  platform: EnumPlatformType.ANDROID,
  type: EnumAppType.APP,
  source: EnumAppSource.PLAY_STORE,
  description: `PandaVPN Lite – Fast, Free, Secure & Private VPN for Streaming & Gaming.\n\nGet unlimited browsing, bypass geo-restrictions, and enjoy a smooth, high-speed VPN. Unblock websites, stream content, and game without lag — trusted by millions worldwide!\n\n✅ No-Logs Policy – We never track, store, or share your data.\n✅ Military Grade Encryption – 256-bit AES encryption for top security.\n✅ Fast & Stable Connections – 3,000+ high-speed servers in 80+ countries.\n✅ Truly Free Servers – Available for indefinite free use with no ads.\n✅ 3-Day Premium Trial – Try our premium features, risk-free!\n✅ Split Tunneling – Control which apps use the VPN.`,
  summary:
    'PandaVPN Lite is a fast, free VPN app offering 3000+ servers across 80+ countries, military-grade encryption, and unlimited bandwidth.',
  latest_news: `The #1 Free Unlimited Proxy Just Got Better!\n1. New Subscription UI: Cleaner layout with accurate local pricing.\n2. Visual Update: Simplified connect button & improved text alignment.\n3. Fixed: Resolved pricing bugs and enhanced stability.`,
  header_image:
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=900&h=400&fit=crop',
  icon: 'https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=96&h=96&fit=crop',
  genre: 'Tools',
  youtube_id: null,
  os_version: 'Android 5.0+',
  screenshots: [
    'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=300&h=600&fit=crop',
    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=300&h=600&fit=crop',
    'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=300&h=600&fit=crop',
    'https://images.unsplash.com/photo-1618761714954-0b8cd0026356?w=300&h=600&fit=crop',
    'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=300&h=600&fit=crop',
  ],
  developer: 'PandaVPN Official',
  app_tags: ['vpn', 'privacy', 'security', 'proxy', 'free-vpn'],
  version: '6.5.2',
  latest_version: '6.5.2',
  show_in_slider: true,
  updated: 'Jan 16, 2026',
  status: EnumAppStatus.PUBLISH,
  url: 'https://play.google.com/store/apps/details?id=com.expand.pandavpn',
  package_name: 'com.expand.pandavpn',
  installs: '50,000,000+',
  score_text: '4.4',
  ratings: 1873274,
  reviews: 1873274,
  published_date: '2020-03-15',
  size: '10 MB',
  is_verified: true,
  short_mode: 'VIP Unlocked',
  links: [
    {
      name: 'Google Play',
      link: 'https://play.google.com',
      type: 'play_store',
      size: '10 MB',
    },
    {
      name: 'Direct Download',
      link: '/download/pandavpn-lite.apk',
      type: 'apk',
      size: '10 MB',
      note: 'v6.5.2',
    },
  ],
  modders: [
    {
      title: 'VIP Unlocked',
      descriptions: 'Premium subscription features unlocked for free.',
    },
  ],
  categories: [
    { id: '1', name: 'Tools', slug: 'tools' },
    { id: '2', name: 'VPN', slug: 'vpn' },
  ],
  tags: [
    { id: '1', name: 'Free VPN', slug: 'free-vpn' },
    { id: '2', name: 'Privacy', slug: 'privacy' },
    { id: '3', name: 'Security', slug: 'security' },
  ],
  last_version_checked_at: '2026-04-01T10:00:00Z',
};

// ─── Card datasets ───────────────────────────────────────────────────────────

export const relatedApps: AppCardData[] = [
  {
    id: '1',
    name: 'Fonxy VPN',
    slug: 'fonxy-vpn',
    icon: 'https://images.unsplash.com/photo-1603366615917-1fa6dad5c4fa?w=96&h=96&fit=crop',
    genre: 'Tools',
    score_text: '4.5',
    ratings: 123456,
    size: '24.3 MB',
    short_mode: 'Pro Unlocked',
    is_verified: true,
  },
  {
    id: '2',
    name: 'Ling – Easy Language Lessons',
    slug: 'ling-language-lessons',
    icon: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=96&h=96&fit=crop',
    genre: 'Education',
    score_text: '4.3',
    ratings: 89000,
    size: '67.1 MB',
  },
  {
    id: '3',
    name: 'Quizlet',
    slug: 'quizlet',
    icon: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=96&h=96&fit=crop',
    genre: 'Education',
    score_text: '4.6',
    ratings: 340000,
    size: '52 MB',
    short_mode: 'Premium Unlocked',
    is_verified: true,
  },
  {
    id: '4',
    name: 'SimCity BuildIt',
    slug: 'simcity-buildit',
    icon: 'https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=96&h=96&fit=crop',
    genre: 'Games',
    score_text: '4.2',
    ratings: 1480000,
    size: '148 MB',
    short_mode: 'MOD Menu',
    is_verified: true,
  },
  {
    id: '5',
    name: 'Matching Story',
    slug: 'matching-story',
    icon: 'https://images.unsplash.com/photo-1559181567-c3190ca9d222?w=96&h=96&fit=crop',
    genre: 'Games',
    score_text: '4.1',
    ratings: 56700,
    size: '230 MB',
    short_mode: 'Unlimited Coins',
  },
  {
    id: '6',
    name: 'Block Blast Adventure Master',
    slug: 'block-blast-adventure',
    icon: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=96&h=96&fit=crop',
    genre: 'Games',
    score_text: '4.4',
    ratings: 2100000,
    size: '95.2 MB',
    short_mode: 'Unlimited Lives',
    is_verified: true,
  },
];

export const recommendedApps: AppCardData[] = [
  {
    id: '7',
    name: 'TurboVPN',
    slug: 'turbo-vpn',
    icon: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=96&h=96&fit=crop',
    genre: 'Tools',
    score_text: '4.3',
    ratings: 950000,
    size: '22 MB',
    short_mode: 'Premium Unlocked',
    is_verified: true,
  },
  {
    id: '8',
    name: 'NordVPN',
    slug: 'nordvpn',
    icon: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=96&h=96&fit=crop',
    genre: 'Tools',
    score_text: '4.7',
    ratings: 2300000,
    size: '38 MB',
    is_verified: true,
  },
  {
    id: '9',
    name: 'Hotspot Shield VPN',
    slug: 'hotspot-shield-vpn',
    icon: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=96&h=96&fit=crop',
    genre: 'Tools',
    score_text: '4.2',
    ratings: 1800000,
    size: '29 MB',
    short_mode: 'Elite Unlocked',
    is_verified: true,
  },
  {
    id: '10',
    name: 'ExpressVPN',
    slug: 'expressvpn',
    icon: 'https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=96&h=96&fit=crop',
    genre: 'Tools',
    score_text: '4.5',
    ratings: 1500000,
    size: '31 MB',
    is_verified: true,
  },
];

export const similarApps: AppCardData[] = [
  {
    id: '11',
    name: 'ProtonVPN',
    slug: 'protonvpn',
    icon: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=96&h=96&fit=crop',
    genre: 'Tools',
    score_text: '4.6',
    ratings: 780000,
    size: '44 MB',
    is_verified: true,
  },
  {
    id: '12',
    name: 'Windscribe VPN',
    slug: 'windscribe-vpn',
    icon: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=96&h=96&fit=crop',
    genre: 'Tools',
    score_text: '4.4',
    ratings: 320000,
    size: '27 MB',
    short_mode: 'Pro Unlocked',
  },
  {
    id: '13',
    name: 'CyberGhost VPN',
    slug: 'cyberghost-vpn',
    icon: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=96&h=96&fit=crop',
    genre: 'Tools',
    score_text: '4.3',
    ratings: 540000,
    size: '35 MB',
    is_verified: true,
  },
  {
    id: '14',
    name: 'Surfshark VPN',
    slug: 'surfshark-vpn',
    icon: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=96&h=96&fit=crop',
    genre: 'Tools',
    score_text: '4.5',
    ratings: 890000,
    size: '33 MB',
    short_mode: 'Premium Unlocked',
    is_verified: true,
  },
];
