// lib/mock-data.ts
//
// Refactored to use the new AppBody type from lib/types.
//
// Shape changes only — NO content values were modified:
//   title      → name
//   banner     → header_image  (empty string → null)
//   downloads  → installs      (number → formatted string)
//   extraInfo  → short_mode
//   isVerified → is_verified
//   updatedAt  → updated
//   releaseDate→ published_date
//   platform   → platform      (string literals match EnumPlatformType values)
//   rating     → score_text    (number → string)
//   (no slug needed for list items; added as empty string for minimal compliance)
//
// Fields that exist in App but NOT in AppBody are dropped:
//   badge, featured  — UI-only concerns, not in AppBody
//
// Required AppBody fields that weren't in App are given safe defaults:
//   source        → EnumAppSource.PLAY_STORE (all items)
//   description   → '' (not available in list context)
//   os_version    → '' (not available in list context)
//   url           → ''
//   package_name  → ''
//   score_text    → String(rating) or '0'
import { AppBody, EnumAppSource, EnumPlatformType } from './types.app';

// ─── HeroSlide type ────────────────────────────────────────────────────────
// Kept as a local type since it has extra hero-specific fields (badge, featured).
// It extends AppBody so components that accept AppBody accept HeroSlide too.
export interface HeroSlide extends AppBody {
  badge?: string;
  featured?: boolean;
}

// ─── Shared AppBody defaults for list items ────────────────────────────────
// Reduces boilerplate — every list entry spreads this and overrides specifics.
const LIST_DEFAULTS = {
  source: EnumAppSource.PLAY_STORE,
  description: '',
  os_version: '',
  url: '',
  package_name: '',
} as const;

// ─── Helper: format downloads number to installs string ───────────────────
function toInstalls(n: number): string {
  if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(0)}B+`;
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(0)}M+`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(0)}K+`;
  return String(n);
}

// ─── Category type is unchanged ────────────────────────────────────────────
export interface Category {
  id: string;
  title: string;
  icon: string;
  color: string;
  count: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// HERO SLIDES
// ═══════════════════════════════════════════════════════════════════════════
export const heroSlides: HeroSlide[] = [
  {
    ...LIST_DEFAULTS,
    id: '1-android',
    name: 'Minecraft Premium',
    icon: 'https://images.unsplash.com/photo-1587573089734-09cb69c0f2b4?w=100&h=100&fit=crop',
    header_image:
      'https://images.unsplash.com/photo-1587573089734-09cb69c0f2b4?w=800&h=400&fit=crop',
    installs: toInstalls(50000000),
    short_mode: 'Premium Unlocked',
    version: '1.0',
    genre: 'Games',
    score_text: '4.8',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
    badge: 'Trending',
    featured: true,
  },
  {
    ...LIST_DEFAULTS,
    id: '1-windows',
    name: 'Minecraft Premium',
    icon: 'https://images.unsplash.com/photo-1587573089734-09cb69c0f2b4?w=100&h=100&fit=crop',
    header_image:
      'https://images.unsplash.com/photo-1587573089734-09cb69c0f2b4?w=800&h=400&fit=crop',
    installs: toInstalls(50000000),
    short_mode: 'Premium Unlocked',
    version: '1.0',
    genre: 'Games',
    score_text: '4.8',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
    badge: 'Trending',
    featured: true,
  },
  {
    ...LIST_DEFAULTS,
    id: '2-windows',
    name: 'Adobe Photoshop',
    icon: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=100&h=100&fit=crop',
    header_image:
      'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&h=400&fit=crop',
    installs: toInstalls(25000000),
    short_mode: 'Full Version',
    version: '1.0',
    genre: 'Design',
    score_text: '4.9',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
    badge: "Editor's Choice",
  },
  {
    ...LIST_DEFAULTS,
    id: '2-apple',
    name: 'Adobe Photoshop',
    icon: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=100&h=100&fit=crop',
    header_image:
      'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&h=400&fit=crop',
    installs: toInstalls(25000000),
    short_mode: 'Full Version',
    version: '1.0',
    genre: 'Design',
    score_text: '4.9',
    is_verified: true,
    platform: EnumPlatformType.IOS,
    badge: "Editor's Choice",
  },
  {
    ...LIST_DEFAULTS,
    id: '3-android',
    name: 'Spotify Premium',
    icon: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=100&h=100&fit=crop',
    header_image:
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=800&h=400&fit=crop',
    installs: toInstalls(100000000),
    short_mode: 'No Ads',
    version: '1.0',
    genre: 'Music',
    score_text: '4.7',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
    badge: 'Popular',
  },
  {
    ...LIST_DEFAULTS,
    id: '3-windows',
    name: 'Spotify Premium',
    icon: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=100&h=100&fit=crop',
    header_image:
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=800&h=400&fit=crop',
    installs: toInstalls(100000000),
    short_mode: 'No Ads',
    version: '1.0',
    genre: 'Music',
    score_text: '4.7',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
    badge: 'Popular',
  },
  {
    ...LIST_DEFAULTS,
    id: '3-apple',
    name: 'Spotify Premium',
    icon: 'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=100&h=100&fit=crop',
    header_image:
      'https://images.unsplash.com/photo-1614680376593-902f74cf0d41?w=800&h=400&fit=crop',
    installs: toInstalls(100000000),
    short_mode: 'No Ads',
    version: '1.0',
    genre: 'Music',
    score_text: '4.7',
    is_verified: true,
    platform: EnumPlatformType.IOS,
    badge: 'Popular',
  },
  {
    ...LIST_DEFAULTS,
    id: '4-android',
    name: 'Notion',
    icon: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=100&h=100&fit=crop',
    header_image:
      'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=400&fit=crop',
    installs: toInstalls(35000000),
    short_mode: 'Pro Features',
    version: '1.0',
    genre: 'Productivity',
    score_text: '4.6',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
    badge: 'New',
  },
  {
    ...LIST_DEFAULTS,
    id: '4-windows',
    name: 'Notion',
    icon: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=100&h=100&fit=crop',
    header_image:
      'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=400&fit=crop',
    installs: toInstalls(35000000),
    short_mode: 'Pro Features',
    version: '1.0',
    genre: 'Productivity',
    score_text: '4.6',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
    badge: 'New',
  },
  {
    ...LIST_DEFAULTS,
    id: '4-apple',
    name: 'Notion',
    icon: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=100&h=100&fit=crop',
    header_image:
      'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&h=400&fit=crop',
    installs: toInstalls(35000000),
    short_mode: 'Pro Features',
    version: '1.0',
    genre: 'Productivity',
    score_text: '4.6',
    is_verified: true,
    platform: EnumPlatformType.IOS,
    badge: 'New',
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// POPULAR APPS
// ═══════════════════════════════════════════════════════════════════════════
export const popularApps: AppBody[] = [
  {
    ...LIST_DEFAULTS,
    id: 'pa1',
    name: 'Instagram Pro',
    icon: 'https://images.unsplash.com/photo-1611262588024-d12430b98920?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(15000000),
    short_mode: 'Premium Unlocked',
    version: '1.0',
    genre: 'Social',
    score_text: '4.5',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa2-android',
    name: 'Canva Pro',
    icon: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(25000000),
    short_mode: 'Full Access',
    version: '1.0',
    genre: 'Design',
    score_text: '4.8',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa2-apple',
    name: 'Canva Pro',
    icon: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(25000000),
    short_mode: 'Full Access',
    version: '1.0',
    genre: 'Design',
    score_text: '4.8',
    is_verified: true,
    platform: EnumPlatformType.IOS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa3-android',
    name: 'Netflix Premium',
    icon: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(50000000),
    short_mode: '4K Streaming',
    version: '1.0',
    genre: 'Entertainment',
    score_text: '4.7',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa3-windows',
    name: 'Netflix Premium',
    icon: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(50000000),
    short_mode: '4K Streaming',
    version: '1.0',
    genre: 'Entertainment',
    score_text: '4.7',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa4',
    name: 'Telegram X',
    icon: 'https://images.unsplash.com/photo-1611606063065-ee7946f0787a?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(100000000),
    short_mode: 'Modded',
    version: '1.0',
    genre: 'Communication',
    score_text: '4.6',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa5',
    name: 'YouTube Vanced',
    icon: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(75000000),
    short_mode: 'Ad-Free',
    version: '1.0',
    genre: 'Entertainment',
    score_text: '4.9',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa6-windows',
    name: 'Microsoft Office',
    icon: 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(200000000),
    short_mode: '365 Activated',
    version: '1.0',
    genre: 'Productivity',
    score_text: '4.5',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa6-android',
    name: 'Microsoft Office',
    icon: 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(200000000),
    short_mode: '365 Activated',
    version: '1.0',
    genre: 'Productivity',
    score_text: '4.5',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa6-apple',
    name: 'Microsoft Office',
    icon: 'https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(200000000),
    short_mode: '365 Activated',
    version: '1.0',
    genre: 'Productivity',
    score_text: '4.5',
    is_verified: true,
    platform: EnumPlatformType.IOS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa7-android',
    name: 'Discord Nitro',
    icon: 'https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(30000000),
    short_mode: 'Unlocked',
    version: '1.0',
    genre: 'Communication',
    score_text: '4.7',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa7-windows',
    name: 'Discord Nitro',
    icon: 'https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(30000000),
    short_mode: 'Unlocked',
    version: '1.0',
    genre: 'Communication',
    score_text: '4.7',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa7-apple',
    name: 'Discord Nitro',
    icon: 'https://images.unsplash.com/photo-1614680376408-81e91ffe3db7?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(30000000),
    short_mode: 'Unlocked',
    version: '1.0',
    genre: 'Communication',
    score_text: '4.7',
    is_verified: true,
    platform: EnumPlatformType.IOS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa8-android',
    name: 'Lightroom Pro',
    icon: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(20000000),
    short_mode: 'Premium',
    version: '1.0',
    genre: 'Photography',
    score_text: '4.6',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pa8-apple',
    name: 'Lightroom Pro',
    icon: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(20000000),
    short_mode: 'Premium',
    version: '1.0',
    genre: 'Photography',
    score_text: '4.6',
    is_verified: true,
    platform: EnumPlatformType.IOS,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// POPULAR GAMES
// ═══════════════════════════════════════════════════════════════════════════
export const popularGames: AppBody[] = [
  {
    ...LIST_DEFAULTS,
    id: 'pg1-windows',
    name: 'GTA V Premium',
    icon: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(120000000),
    short_mode: 'All DLCs',
    version: '1.0',
    genre: 'Action',
    score_text: '4.9',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg1-android',
    name: 'GTA V Premium',
    icon: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(120000000),
    short_mode: 'All DLCs',
    version: '1.0',
    genre: 'Action',
    score_text: '4.9',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg2',
    name: 'PUBG Mobile',
    icon: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(500000000),
    short_mode: 'UC Unlocked',
    version: '1.0',
    genre: 'Battle Royale',
    score_text: '4.5',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg3-windows',
    name: 'FIFA 24',
    icon: 'https://images.unsplash.com/photo-1493711662062-fa541f7f3d24?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(80000000),
    short_mode: 'Full Version',
    version: '1.0',
    genre: 'Sports',
    score_text: '4.4',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg3-android',
    name: 'FIFA 24',
    icon: 'https://images.unsplash.com/photo-1493711662062-fa541f7f3d24?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(80000000),
    short_mode: 'Full Version',
    version: '1.0',
    genre: 'Sports',
    score_text: '4.4',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg4-android',
    name: 'Clash of Clans',
    icon: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(500000000),
    short_mode: 'Gems Mod',
    version: '1.0',
    genre: 'Strategy',
    score_text: '4.6',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg4-apple',
    name: 'Clash of Clans',
    icon: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(500000000),
    short_mode: 'Gems Mod',
    version: '1.0',
    genre: 'Strategy',
    score_text: '4.6',
    is_verified: true,
    platform: EnumPlatformType.IOS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg5-android',
    name: 'Call of Duty Mobile',
    icon: 'https://images.unsplash.com/photo-1552820728-8b83bb6b2b34?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(300000000),
    short_mode: 'All Skins',
    version: '1.0',
    genre: 'FPS',
    score_text: '4.7',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg5-apple',
    name: 'Call of Duty Mobile',
    icon: 'https://images.unsplash.com/photo-1552820728-8b83bb6b2b34?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(300000000),
    short_mode: 'All Skins',
    version: '1.0',
    genre: 'FPS',
    score_text: '4.7',
    is_verified: true,
    platform: EnumPlatformType.IOS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg6-android',
    name: 'Asphalt 9',
    icon: 'https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(100000000),
    short_mode: 'Unlimited Tokens',
    version: '1.0',
    genre: 'Racing',
    score_text: '4.5',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg6-windows',
    name: 'Asphalt 9',
    icon: 'https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(100000000),
    short_mode: 'Unlimited Tokens',
    version: '1.0',
    genre: 'Racing',
    score_text: '4.5',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg7-android',
    name: 'Among Us',
    icon: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(200000000),
    short_mode: 'All Skins',
    version: '1.0',
    genre: 'Party',
    score_text: '4.4',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg7-windows',
    name: 'Among Us',
    icon: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(200000000),
    short_mode: 'All Skins',
    version: '1.0',
    genre: 'Party',
    score_text: '4.4',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg7-apple',
    name: 'Among Us',
    icon: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(200000000),
    short_mode: 'All Skins',
    version: '1.0',
    genre: 'Party',
    score_text: '4.4',
    is_verified: true,
    platform: EnumPlatformType.IOS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg8-android',
    name: 'Roblox Mod',
    icon: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(400000000),
    short_mode: 'Robux Mod',
    version: '1.0',
    genre: 'Sandbox',
    score_text: '4.5',
    is_verified: true,
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'pg8-windows',
    name: 'Roblox Mod',
    icon: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(400000000),
    short_mode: 'Robux Mod',
    version: '1.0',
    genre: 'Sandbox',
    score_text: '4.5',
    is_verified: true,
    platform: EnumPlatformType.WINDOWS,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// LATEST UPDATED APPS
// ═══════════════════════════════════════════════════════════════════════════
export const latestUpdatedApps: AppBody[] = [
  {
    ...LIST_DEFAULTS,
    id: 'lua1',
    name: 'WhatsApp Plus',
    icon: 'https://images.unsplash.com/photo-1611746872915-64382b5c76da?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(100000000),
    short_mode: 'v17.40',
    genre: 'Communication',
    version: '1.0',
    updated: '2024-01-15',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'lua2',
    name: 'GBInstagram',
    icon: 'https://images.unsplash.com/photo-1611262588019-db6b2032b687?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(50000000),
    short_mode: 'v3.20',
    genre: 'Social',
    version: '1.0',
    updated: '2024-01-14',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'lua3',
    name: 'TikTok Mod',
    icon: 'https://images.unsplash.com/photo-1611605698335-8b1569810432?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(75000000),
    short_mode: 'v32.0',
    genre: 'Social',
    version: '1.0',
    updated: '2024-01-13',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'lua4-windows',
    name: 'Zoom Pro',
    icon: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(300000000),
    short_mode: 'v5.17',
    genre: 'Business',
    version: '1.0',
    updated: '2024-01-12',
    score_text: '0',
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'lua4-android',
    name: 'Zoom Pro',
    icon: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(300000000),
    short_mode: 'v5.17',
    genre: 'Business',
    version: '1.0',
    updated: '2024-01-12',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'lua4-apple',
    name: 'Zoom Pro',
    icon: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(300000000),
    short_mode: 'v5.17',
    genre: 'Business',
    version: '1.0',
    updated: '2024-01-12',
    score_text: '0',
    platform: EnumPlatformType.IOS,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// NEW RELEASE APPS
// ═══════════════════════════════════════════════════════════════════════════
export const newReleaseApps: AppBody[] = [
  {
    ...LIST_DEFAULTS,
    id: 'nra1-android',
    name: 'AI Chat Pro',
    icon: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(5000000),
    short_mode: 'GPT-4 Enabled',
    genre: 'AI',
    version: '1.0',
    published_date: '2024-01-10',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nra1-apple',
    name: 'AI Chat Pro',
    icon: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(5000000),
    short_mode: 'GPT-4 Enabled',
    genre: 'AI',
    version: '1.0',
    published_date: '2024-01-10',
    score_text: '0',
    platform: EnumPlatformType.IOS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nra2-android',
    name: 'Focus Timer',
    icon: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(1000000),
    short_mode: 'Premium',
    genre: 'Productivity',
    version: '1.0',
    published_date: '2024-01-09',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nra2-apple',
    name: 'Focus Timer',
    icon: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(1000000),
    short_mode: 'Premium',
    genre: 'Productivity',
    version: '1.0',
    published_date: '2024-01-09',
    score_text: '0',
    platform: EnumPlatformType.IOS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nra3',
    name: 'PhotoAI Editor',
    icon: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(2000000),
    short_mode: 'Full Version',
    genre: 'Photography',
    version: '1.0',
    published_date: '2024-01-08',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nra4-windows',
    name: 'Code Editor Pro',
    icon: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(500000),
    short_mode: 'All Languages',
    genre: 'Development',
    version: '1.0',
    published_date: '2024-01-07',
    score_text: '0',
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nra4-android',
    name: 'Code Editor Pro',
    icon: 'https://images.unsplash.com/photo-1542831371-29b0f74f9713?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(500000),
    short_mode: 'All Languages',
    genre: 'Development',
    version: '1.0',
    published_date: '2024-01-07',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// LATEST UPDATED GAMES
// ═══════════════════════════════════════════════════════════════════════════
export const latestUpdatedGames: AppBody[] = [
  {
    ...LIST_DEFAULTS,
    id: 'lug1',
    name: 'Free Fire MAX',
    icon: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(200000000),
    short_mode: 'v2.100',
    genre: 'Battle Royale',
    version: '1.0',
    updated: '2024-01-15',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'lug2',
    name: 'Mobile Legends',
    icon: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(300000000),
    short_mode: 'v1.8',
    genre: 'MOBA',
    version: '1.0',
    updated: '2024-01-14',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'lug3-android',
    name: 'Genshin Impact',
    icon: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(150000000),
    short_mode: 'v4.3',
    genre: 'RPG',
    version: '1.0',
    updated: '2024-01-13',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'lug3-windows',
    name: 'Genshin Impact',
    icon: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(150000000),
    short_mode: 'v4.3',
    genre: 'RPG',
    version: '1.0',
    updated: '2024-01-13',
    score_text: '0',
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'lug4-android',
    name: 'Brawl Stars',
    icon: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(250000000),
    short_mode: 'v48',
    genre: 'Action',
    version: '1.0',
    updated: '2024-01-12',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'lug4-apple',
    name: 'Brawl Stars',
    icon: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(250000000),
    short_mode: 'v48',
    genre: 'Action',
    version: '1.0',
    updated: '2024-01-12',
    score_text: '0',
    platform: EnumPlatformType.IOS,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// NEW RELEASE GAMES
// ═══════════════════════════════════════════════════════════════════════════
export const newReleaseGames: AppBody[] = [
  {
    ...LIST_DEFAULTS,
    id: 'nrg1-android',
    name: 'Epic Quest',
    icon: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(500000),
    short_mode: 'Full Game',
    genre: 'RPG',
    version: '1.0',
    published_date: '2024-01-11',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nrg1-windows',
    name: 'Epic Quest',
    icon: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(500000),
    short_mode: 'Full Game',
    genre: 'RPG',
    version: '1.0',
    published_date: '2024-01-11',
    score_text: '0',
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nrg2',
    name: 'Drift King',
    icon: 'https://images.unsplash.com/photo-1547394765-185e1e68f34e?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(200000),
    short_mode: 'All Cars',
    genre: 'Racing',
    version: '1.0',
    published_date: '2024-01-10',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nrg3',
    name: 'Space Wars',
    icon: 'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(150000),
    short_mode: 'Premium',
    genre: 'Sci-Fi',
    version: '1.0',
    published_date: '2024-01-09',
    score_text: '0',
    platform: EnumPlatformType.WINDOWS,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nrg4-android',
    name: 'Puzzle Master',
    icon: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(80000),
    short_mode: 'Ad-Free',
    genre: 'Puzzle',
    version: '1.0',
    published_date: '2024-01-08',
    score_text: '0',
    platform: EnumPlatformType.ANDROID,
  },
  {
    ...LIST_DEFAULTS,
    id: 'nrg4-apple',
    name: 'Puzzle Master',
    icon: 'https://images.unsplash.com/photo-1606503153255-59d8b8b82176?w=100&h=100&fit=crop',
    header_image: null,
    installs: toInstalls(80000),
    short_mode: 'Ad-Free',
    genre: 'Puzzle',
    version: '1.0',
    published_date: '2024-01-08',
    score_text: '0',
    platform: EnumPlatformType.IOS,
  },
];

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORIES — unchanged, Category interface is project-local
// ═══════════════════════════════════════════════════════════════════════════
export const appCategories: Category[] = [
  {
    id: 'ac1',
    title: 'Art & Design',
    icon: 'palette',
    color: '#FF6B6B',
    count: 245,
  },
  {
    id: 'ac2',
    title: 'Auto & Vehicles',
    icon: 'car',
    color: '#4ECDC4',
    count: 132,
  },
  { id: 'ac3', title: 'Beauty', icon: 'sparkles', color: '#FFE66D', count: 98 },
  {
    id: 'ac4',
    title: 'Books & Reference',
    icon: 'book-open',
    color: '#A8E6CF',
    count: 317,
  },
  {
    id: 'ac5',
    title: 'Business',
    icon: 'briefcase',
    color: '#DDA0DD',
    count: 412,
  },
  { id: 'ac6', title: 'Comics', icon: 'book', color: '#87CEEB', count: 74 },
  {
    id: 'ac7',
    title: 'Communication',
    icon: 'message-circle',
    color: '#FFB347',
    count: 189,
  },
  { id: 'ac8', title: 'Dating', icon: 'heart', color: '#98D8C8', count: 56 },
  {
    id: 'ac9',
    title: 'Education',
    icon: 'graduation-cap',
    color: '#FF6B6B',
    count: 503,
  },
  {
    id: 'ac10',
    title: 'Emulator',
    icon: 'monitor',
    color: '#4ECDC4',
    count: 41,
  },
  {
    id: 'ac11',
    title: 'Entertainment',
    icon: 'film',
    color: '#FFE66D',
    count: 567,
  },
  {
    id: 'ac12',
    title: 'Events',
    icon: 'calendar',
    color: '#A8E6CF',
    count: 88,
  },
  {
    id: 'ac13',
    title: 'Finance',
    icon: 'bar-chart-2',
    color: '#DDA0DD',
    count: 276,
  },
  {
    id: 'ac14',
    title: 'Food & Drink',
    icon: 'utensils',
    color: '#87CEEB',
    count: 194,
  },
  {
    id: 'ac15',
    title: 'Health & Fitness',
    icon: 'activity',
    color: '#FFB347',
    count: 348,
  },
  {
    id: 'ac16',
    title: 'House & Home',
    icon: 'home',
    color: '#98D8C8',
    count: 162,
  },
  {
    id: 'ac17',
    title: 'Libraries & Demo',
    icon: 'layers',
    color: '#FF6B6B',
    count: 29,
  },
  { id: 'ac18', title: 'Lifestyle', icon: 'sun', color: '#4ECDC4', count: 221 },
  {
    id: 'ac19',
    title: 'Maps & Navigation',
    icon: 'map',
    color: '#FFE66D',
    count: 137,
  },
  { id: 'ac20', title: 'Medical', icon: 'cross', color: '#A8E6CF', count: 183 },
  { id: 'ac21', title: 'Music', icon: 'music', color: '#DDA0DD', count: 187 },
  {
    id: 'ac22',
    title: 'Music & Audio',
    icon: 'headphones',
    color: '#87CEEB',
    count: 154,
  },
  {
    id: 'ac23',
    title: 'News & Magazines',
    icon: 'newspaper',
    color: '#FFB347',
    count: 209,
  },
  {
    id: 'ac24',
    title: 'Parenting',
    icon: 'users',
    color: '#98D8C8',
    count: 67,
  },
  {
    id: 'ac25',
    title: 'Personalization',
    icon: 'sliders',
    color: '#FF6B6B',
    count: 298,
  },
  {
    id: 'ac26',
    title: 'Photography',
    icon: 'camera',
    color: '#4ECDC4',
    count: 324,
  },
  {
    id: 'ac27',
    title: 'Productivity',
    icon: 'check-square',
    color: '#FFE66D',
    count: 412,
  },
  {
    id: 'ac28',
    title: 'Shopping',
    icon: 'shopping-cart',
    color: '#A8E6CF',
    count: 241,
  },
  {
    id: 'ac29',
    title: 'Social',
    icon: 'share-2',
    color: '#DDA0DD',
    count: 298,
  },
  { id: 'ac30', title: 'Sport', icon: 'trophy', color: '#87CEEB', count: 176 },
  { id: 'ac31', title: 'Tools', icon: 'tool', color: '#FFB347', count: 534 },
  {
    id: 'ac32',
    title: 'Travel & Local',
    icon: 'navigation',
    color: '#98D8C8',
    count: 259,
  },
  {
    id: 'ac33',
    title: 'Video Players & Editors',
    icon: 'play-circle',
    color: '#FF6B6B',
    count: 143,
  },
  { id: 'ac34', title: 'Weather', icon: 'cloud', color: '#4ECDC4', count: 89 },
];

export const gameCategories: Category[] = [
  { id: 'gc1', title: 'Action', icon: 'zap', color: '#FF6B6B', count: 892 },
  {
    id: 'gc2',
    title: 'Adventure',
    icon: 'compass',
    color: '#4ECDC4',
    count: 456,
  },
  {
    id: 'gc3',
    title: 'Arcade',
    icon: 'joystick',
    color: '#FFE66D',
    count: 378,
  },
  { id: 'gc4', title: 'Board', icon: 'grid', color: '#A8E6CF', count: 214 },
  { id: 'gc5', title: 'Card', icon: 'layers', color: '#DDA0DD', count: 167 },
  {
    id: 'gc6',
    title: 'Casino',
    icon: 'dollar-sign',
    color: '#87CEEB',
    count: 203,
  },
  { id: 'gc7', title: 'Casual', icon: 'smile', color: '#FFB347', count: 521 },
  {
    id: 'gc8',
    title: 'Educational',
    icon: 'book-open',
    color: '#98D8C8',
    count: 289,
  },
  { id: 'gc9', title: 'Music', icon: 'music', color: '#FF6B6B', count: 134 },
  {
    id: 'gc10',
    title: 'NSFW',
    icon: 'alert-octagon',
    color: '#4ECDC4',
    count: 47,
  },
  { id: 'gc11', title: 'Puzzle', icon: 'cpu', color: '#FFE66D', count: 678 },
  {
    id: 'gc12',
    title: 'Racing',
    icon: 'navigation',
    color: '#A8E6CF',
    count: 234,
  },
  {
    id: 'gc13',
    title: 'Role Playing',
    icon: 'user',
    color: '#DDA0DD',
    count: 345,
  },
  { id: 'gc14', title: 'RPG', icon: 'shield', color: '#87CEEB', count: 312 },
  {
    id: 'gc15',
    title: 'Simulation',
    icon: 'box',
    color: '#FFB347',
    count: 432,
  },
  { id: 'gc16', title: 'Sports', icon: 'award', color: '#98D8C8', count: 567 },
  {
    id: 'gc17',
    title: 'Strategy',
    icon: 'target',
    color: '#FF6B6B',
    count: 289,
  },
  {
    id: 'gc18',
    title: 'Trivia',
    icon: 'help-circle',
    color: '#4ECDC4',
    count: 198,
  },
  { id: 'gc19', title: 'Word', icon: 'type', color: '#FFE66D', count: 156 },
];
